### ISSUE TITLE
Game state machine (enable win and game over)

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation#13]
Game needs a state machine to start a game and decide when the game is over.

EDIT (by @David-Estevez) States:
 * [x] Init
 * [x] Game
 * [x] Dead
 * [x] Respawn
 * [x] Logout

**Comment by David-Estevez** [comment]
I have a design for a generic FSM that can be used in other projects apart from this one, eliminating the need for redundant code and using YARP (or any other thing) for state machine flow control.

If the design works, I'll do a post about it in the robot devastation wiki.

**Comment by David-Estevez** [comment]
Add an initial state to the game FSM (commit 53627f0)

**Comment by David-Estevez** [comment]
More info for Game State Machine implementation:
# Game State
 * If health == 0 -> Dead State

While in game:
 * If hit -> health decreases
 * If moves -> robot moves
 * if hits target -> target loses health
 * if esc -> ??

# Dead State
When time runs out:
 * If press enter -> respawn
 * If press escape -> logout
Otherwise -> time decreases

# Respawn
* Health set to max
* Go to Game State again

# Logout
* Log out from server

**Comment by David-Estevez** [comment]
Respawn and Logout are not really states, but things to do in a transition, so they can be merged with the Dead state.

**Comment by David-Estevez** [comment]
Added DeadState (with Respawn & Logout)  in commit e7931c0

**Comment by David-Estevez** [comment]
Currently blocked due to lack of tests for RdProcessorImageEventListener class that is performing strangely in the GameState test.

**Comment by David-Estevez** [comment]
Added GameState (with Logout) in commit 923adf8f7f019b97aef6a1997c02dfc61a66d2d2

This was the last state required to complete the game FSM. Closing this issue.
